stages:
  - sonarqube

variables:
  IMAGE_NAME: umjoshua/demo-app
  IMAGE_TAG: python-app-1.0

test-job:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner
      -Dsonar.projectKey=$CI_PROJECT_PATH_SLUG
      -Dsonar.sources=.
      -Dsonar.host.url=SONAR_HOST
      -Dsonar.login=SONAR_TOKEN