stages:
  - build
  - sonarqube

variables:
  IMAGE_NAME: umjoshua/demo-app
  IMAGE_TAG: python-app-1.0

build-job:
  stage: build
  image: gradle
  script:
    - gradle build
    - gradlew sonarqube
  artifacts:
    when: on_success
    paths:
      - "build/"
    expire_in: 1 days

# test-job:
#   stage: sonarqube
#   image: gradle
#   script:
#     - gradlew sonarqube